name: TachyonRefreshedExample
version: '1.0-SNAPSHOT'
main: es.redactado.tachyonRefreshedExample.TachyonRefreshedExample
api-version: '1.20'
softdepend:
  - packetevents
commands:
  tachyon:
    description: Main command for TachyonRefreshed example
    usage: /tachyon <pos1|pos2|save|load>
    permission: tachyon.use